AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  S3EncryptCheck:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 20
      Role: 'arn:aws:iam::776848677940:role/AWSLambdaVPCAccessExecutionRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
